#invoke make inside following directories and in this order: loader, launch, fib
#move the lib_simpleloader.so and launch binaries inside bin directory
#Provide the command for cleanup
# Default target
run:
	./bin/launch ./test/fib

clean:
	rm -f *.o